services:
  
  otel-collector:
    image: otel/opentelemetry-collector:0.91.0
    restart: always 
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
    - 8888:8888 # Prometheus metrics exposed by the Collector
    - 8889:8889 # Prometheus exporter metrics
    - 4318:4318 # OTLP HTTP receiver
    - 4317:4317 # OTLP gRPC receiver
    depends_on:
      - zipkin
    networks:
      - goapp
      
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
       # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    restart: always
    networks:
      - goapp

  servicoa:
    build: ./servicoA
    container_name: servicoA
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
      - zipkin
    networks:
      - goapp
  servicob:
    build: ./servicoB
    container_name: servicoB
    ports:
      - "8181:8181"
    depends_on:
      - otel-collector
      - zipkin
    networks:
      - goapp

networks:
  goapp:
    driver: bridge