services:
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always 
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
    - 8888:8888 # Prometheus metrics exposed by the Collector
    - 8889:8889 # Prometheus exporter metrics
    - 4317:4317 # OTLP gRPC receiver
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
    - COLLECTOR_OTLP_ENABLED=true
    - COLLECTOR_OTLP_INSECURE=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # Jaeger gRPC receiver
      - "14268:14268" # Jaeger HTTP receiver
    restart: always 
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"   # Prometheus UI
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"   # Grafana UI
    restart: unless-stopped   

  servicoa:
    build: ./servicoA
    container_name: servicoA
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
      - jaeger
      - prometheus
      - grafana
      
  servicob:
    build: ./servicoB
    container_name: servicoB
    ports:
      - "8181:8181"
    depends_on:
      - otel-collector
      - jaeger
      - prometheus
      - grafana